GET http://localhost:5000/api/private

headers: { "authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InljVkM1T1FPWGhnYXZvTW9GeEVRYyJ9.eyJpc3MiOiJodHRwczovL2Rldi1tZDF2N3pwZDFrZmtiZjFkLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJNUWFaQUV1VENpVThOVWxRUEh6djNEbFJnc09MTndYUEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9jb3N0LW1hbmFnZXIuY29tIiwiaWF0IjoxNjk1MzM3Mjc0LCJleHAiOjE2OTU0MjM2NzQsImF6cCI6Ik1RYVpBRXVUQ2lVOE5VbFFQSHp2M0RsUmdzT0xOd1hQIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.GhGkF0Y6OH31OWCNhSACb0YeTXTCI3UU7NFom0bRVlNOpdP9lJ95UljKF3Dho6OVV1-Bkhz0DXGHw7sARf4ckWFgLGVf2RbKvgnS6INKLXKe9jjVtsW5W0o5omRjNhXcda6SYUSsGNJ3J-0awujgRsZGD2MVxZlVHKA_4ygyZrRlvkjisCmJm43cd25ejsP-HOjoO88suFr7MHq-3FjO9P0a-zbK5B_84T_4hpZfjvo7QlUpbx66VvR-3tyGax4ovAdm6cPGybPO6PjKPUvPrGw4dc_TJjSqEPgLyObAs60Ub6gdTDr49qBiEfaowuiuyAzF-SkqfwD8NJ1HXV8HYQ" }